# Generated by Django 5.1.6 on 2025-06-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_applicat_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicat_details',
            name='Documents',
        ),
        migrations.AddField(
            model_name='applicat_details',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Files'),
        ),
    ]
