# Generated by Django 5.1.6 on 2025-06-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_applicat_details_documents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicat_details',
            name='status',
            field=models.CharField(default='Applied', max_length=20, verbose_name=[('Rejected', 'Rejected'), ('Selected', 'Selected'), ('Applied', 'Applied')]),
        ),
    ]
