# Generated by Django 5.1.6 on 2025-06-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_applicat_details_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=30)),
                ('email', models.EmailField(default='', max_length=20)),
                ('password', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='applicat_details',
            name='status',
            field=models.CharField(choices=[('Rejected', 'Rejected'), ('Selected', 'Selected'), ('Applied', 'Applied')], default='Applied', max_length=20),
        ),
    ]
