# Generated by Django 5.1.6 on 2025-06-09 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_user_alter_applicat_details_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicat_details',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.user'),
        ),
    ]
