# Generated by Django 5.1.6 on 2025-06-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_applicat_details_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicat_details',
            name='temp_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
